baseurl = "/"
languageCode = "en"
title = "CFEngine Build"
theme = "cfbs-theme"

enableRobotsTXT = true
syntaxCSS = true

# Number of posts per page
[pagination]
pagerSize = 10

[params.info]
homeTitle = "CFEngine Build" # Title for home page

[params.featured]
modules = ['packages-allowlist-snapshot', 'delete-files', 'promise-type-docker-compose']

[taxonomies]
tag = "tags"
author = "author"

[params.sitemap]
baseUrl = "https://build.cfengine.com"
[markup]
	[markup.highlight]
		noClasses = false
